# Generated by Django 4.2 on 2024-05-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0002_alter_basketitem_user'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='basketitem',
            index=models.Index(fields=['add_datetime'], name='basketapp_b_add_dat_b0487a_idx'),
        ),
    ]
