# Generated by Django 4.2 on 2024-06-08 15:51

import authapp_custom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp_custom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=authapp_custom.models.get_activation_key_expires),
        ),
    ]
